=== minesvieira/PRI-UM/TPC/PRI2019-PG39292-T2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT project-record (dados, workteam, abstract, deliverables?,data) >
<!ELEMENT dados (keyname, title, subtitle, begin_date, end_date, supervisor) >
<!ELEMENT keyname (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor
            plataforma CDATA #REQUIRED>
 <!ELEMENT plataforma (#PCDATA) >


<!ELEMENT workteam (aluno+) >
<!ELEMENT aluno (nome, email, numero) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT numero (#PCDATA) >

<!ELEMENT abstract (paragrafo+) >
<!ELEMENT paragrafo (#PCDATA|negrito|italico|sublinhado|links)* >
<!ELEMENT negrito (#PCDATA) >
<!ELEMENT italico (#PCDATA) >
<!ELEMENT sublinhado (#PCDATA) >
<!ELEMENT links (#PCDATA) >
<!ATTLIST links
            url CDATA #REQUIRED>
            
<!ELEMENT deliverables (deliverable+) >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable
                ficheiro CDATA #REQUIRED>

<!ELEMENT data (#PCDATA) >

=== minesvieira/PRI-UM/PRI2019-PG39292-T2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "file:/C:/Users/Maria/Desktop/MEI/1%C2%BASemestre/PRI/PRI2019-PG39292-T2/pr.dtd">
<project-record>
    <dados>
        <keyname>Maria_MEI2019</keyname>
        <title> Trabalho de casa 2</title>
        <subtitle> XML e DTDS</subtitle>
        <begin_date> Setembro 2019</begin_date>
        <end_date> Setembro 2019</end_date>
        <supervisor plataforma="http://www4.di.uminho.pt/~jcr/"></supervisor>
    </dados>
    <workteam>
        <aluno>
            <nome> Maria Inês Vieira Pinto</nome>
            <email> mariainesvpinto14@hotmail.com </email>
            <numero> PG39292</numero>
        </aluno>
    </workteam>
    <abstract>
        <paragrafo> <negrito> XML</negrito>(Extensible Markup Language) é uma recomendação da W3C para gerar linguagens de marcação para necessidades especiais.</paragrafo>
        <paragrafo> É um dos subtipos da SGML <italico> (acrônimo de Standard Generalized Markup Language ou Linguagem Padronizada de Marcação Genérica)</italico> capaz de descrever diversos tipos de dados. O seu propósito principal é a <sublinhado>facilidade de compartilhamento de informações</sublinhado> por intermédio da internet.</paragrafo>
        <paragrafo> Este TPC foi baseado nesta página: <links url="http://www4.di.uminho.pt/~jcr/XML/didac/xmldocs/PR.htm"></links> em que através da sua estrutura, conseguissemos implementar um ficheiro dtd e xml. </paragrafo>
    </abstract>
    <deliverables>
        <deliverable ficheiro="pr.xml"></deliverable>
        <deliverable ficheiro="pr.dtd"></deliverable>
        <deliverable ficheiro="arq.txt"></deliverable>
        <deliverable ficheiro="agenda.txt"></deliverable>
    </deliverables>
    <data> 5-10-2019</data>
</project-record>
